### ISSUE TITLE
fix the pipeline

### ISSUE THREAD

**Issue by ElectNewt** [ElectNewt/EjemploRop#21]
so it seems that there is something wrong with the pipeline when pushing to nuget, investigate about it and fix it.

**Comment by MattP2001** [comment]
![Image](https://github.com/user-attachments/assets/946e1624-e4e7-44b7-ab44-8b15880f1275)

![Image](https://github.com/user-attachments/assets/5371133f-1c8e-48c2-9100-89de13265bc6)

mmm its not the API key

the Netmentor.ROP is updated but the other 2 arent, so it seems to be the pipeline

**Comment by MattP2001** [comment]
```
name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: "1.7.2"  

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack ROP
      run: dotnet pack src/ROP/ROP.csproj --configuration Release --output ./packages --property:Version=${{ env.PACKAGE_VERSION }}

    - name: Pack ROP.ApiExtensions
      run: dotnet pack src/ROP.ApiExtensions/ROP.ApiExtensions.csproj --configuration Release --output ./packages --property:Version=${{ env.PACKAGE_VERSION }}

    - name: Pack ROP.ApiExtensions.Translations
      run: dotnet pack src/ROP.ApiExtensions.Translations/ROP.ApiExtensions.Translations.csproj --configuration Release --output ./packages --property:Version=${{ env.PACKAGE_VERSION }}

    - name: Publish to NuGet
      run: dotnet nuget push "./packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
```
